import { ChapterData, ModuleData, SandboxTemplate } from '@/types/simulator';

export const CHAPTERS: ChapterData[] = [
  {
    id: 1,
    title: 'Bab 1: Navigasi & Aritmatika Dasar',
    description: 'Fondasi matematika Excel: Tambah (+), Kurang (-), Kali (*), Bagi (/), Persen (%), dan Tanda Kurung ().',
    iconName: 'Calculator',
    moduleIds: [1, 2, 3, 4, 5, 6],
  },
  {
    id: 2,
    title: 'Bab 2: Agregasi & Statistik Esensial',
    description: 'Mengolah sekumpulan data: SUM, AVERAGE, MAX, MIN, COUNT, COUNTA, COUNTBLANK, LARGE, SMALL.',
    iconName: 'BarChart3',
    moduleIds: [7, 8, 9, 10, 11, 12, 13, 14],
  },
  {
    id: 3,
    title: 'Bab 3: Manipulasi Teks & Tanggal',
    description: 'Pembersihan data string & tanggal: PROPER, UPPER, LOWER, &, CONCAT, LEFT, RIGHT, MID, TRIM, LEN.',
    iconName: 'Type',
    moduleIds: [15, 16, 17, 18, 19, 20, 21, 22],
  },
  {
    id: 4,
    title: 'Bab 4: Logika & Pengambilan Keputusan',
    description: 'Kondisi otomatis: IF, Nested IF, AND, OR, COUNTIF, COUNTIFS, SUMIF, SUMIFS, AVERAGEIF.',
    iconName: 'Cpu',
    moduleIds: [23, 24, 25, 26, 27, 28, 29, 30],
  },
  {
    id: 5,
    title: 'Bab 5: Pencarian Data & Lookup',
    description: 'Menghubungkan data antar tabel: VLOOKUP, HLOOKUP, INDEX MATCH, XLOOKUP.',
    iconName: 'Search',
    moduleIds: [31, 32, 33, 34, 35, 36],
  },
  {
    id: 6,
    title: 'Bab 6: Analisis Bisnis & Finansial',
    description: 'Penerapan di dunia kerja: Laporan Laba Rugi, Margin %, Cicilan Pinjaman (PMT), Break Even Point.',
    iconName: 'TrendingUp',
    moduleIds: [37, 38, 39, 40],
  },
];

export const MODULES: ModuleData[] = [
  // ========================================================
  // BAB 1: NAVIGASI & ARITMATIKA DASAR (Modul 1 - 6)
  // ========================================================
  {
    id: 1,
    chapterId: 1,
    title: 'Modul 1: Penjumlahan Pengeluaran Harian (+)',
    category: 'Aritmatika',
    difficulty: 'Pemula',
    scenario: 'Kamu mencatat pengeluaran hari Senin: Biaya Makan Rp25.000 (B2) dan Transportasi Rp15.000 (C2).',
    objective: 'Hitung total pengeluaran hari Senin pada sel D2 dengan menjumlahkan sel B2 dan C2.',
    targetCell: 'D2',
    targetRowNumber: 2,
    targetColKey: 'total',
    targetColLetter: 'D',
    columns: [
      { key: 'hari', label: 'Hari', letter: 'A' },
      { key: 'makan', label: 'Makan (Rp)', letter: 'B' },
      { key: 'transport', label: 'Transport (Rp)', letter: 'C' },
      { key: 'total', label: 'Total (Rp)', letter: 'D' },
    ],
    rows: [
      { rowNumber: 2, values: { hari: 'Senin', makan: 25000, transport: 15000, total: '?' } },
      { rowNumber: 3, values: { hari: 'Selasa', makan: 30000, transport: 15000, total: 45000 } },
      { rowNumber: 4, values: { hari: 'Rabu', makan: 22000, transport: 15000, total: 37000 } },
    ],
    validFormulas: ['=B2+C2', '=C2+B2', '=SUM(B2:C2)', '=SUM(B2,C2)', '=SUM(B2+C2)', '=SUM(B2 + C2)'],
    acceptedAnswers: [40000],
    hints: ['Ketik =B2+C2 pada sel D2 lalu tekan Enter.'],
    explanation: 'Rumus =B2+C2 menjumlahkan Rp25.000 + Rp15.000 = Rp40.000.',
    samplePlaceholder: '=B2+C2',
    theory: {
      concept: 'Semua rumus Excel diawali tanda sama dengan (=). Gunakan simbol + untuk menjumlahkan dua nilai secara langsung.',
      whyItMatters: 'Fondasi penting untuk menghitung transaksi kasir, buku kas pribadi, dan anggaran.',
      syntax: '=sel1 + sel2',
      example: '=B2 + C2',
    },
  },
  {
    id: 2,
    chapterId: 1,
    title: 'Modul 2: Pengurangan Arus Kas (-)',
    category: 'Aritmatika',
    difficulty: 'Pemula',
    scenario: 'Pemasukan bulananmu Rp4.500.000 (B2) dan total pengeluaranmu Rp3.200.000 (C2). Hitung sisa tabunganmu.',
    objective: 'Hitung sisa tabungan pada sel D2 dengan mengurangi Pemasukan (B2) dengan Pengeluaran (C2).',
    targetCell: 'D2',
    targetRowNumber: 2,
    targetColKey: 'sisa',
    targetColLetter: 'D',
    columns: [
      { key: 'bulan', label: 'Bulan', letter: 'A' },
      { key: 'masuk', label: 'Pemasukan (Rp)', letter: 'B' },
      { key: 'keluar', label: 'Pengeluaran (Rp)', letter: 'C' },
      { key: 'sisa', label: 'Sisa Tabungan (Rp)', letter: 'D' },
    ],
    rows: [
      { rowNumber: 2, values: { bulan: 'Januari', masuk: 4500000, keluar: 3200000, sisa: '?' } },
      { rowNumber: 3, values: { bulan: 'Februari', masuk: 4500000, keluar: 2900000, sisa: 1600000 } },
    ],
    validFormulas: ['=B2-C2'],
    acceptedAnswers: [1300000],
    hints: ['Gunakan tanda minus (-). Ketik =B2-C2 lalu tekan Enter.'],
    explanation: 'Rumus =B2-C2 menghasilkan sisa tabungan Rp1.300.000.',
    samplePlaceholder: '=B2-C2',
    theory: {
      concept: 'Simbol minus (-) digunakan untuk mengurangi nilai sel.',
      whyItMatters: 'Kunci dalam menghitung laba bersih (Omset - Biaya) dan selisih angka.',
      syntax: '=sel1 - sel2',
      example: '=B2 - C2',
    },
  },
  {
    id: 3,
    chapterId: 1,
    title: 'Modul 3: Perkalian Belanja Sembako (*)',
    category: 'Aritmatika',
    difficulty: 'Pemula',
    scenario: 'Membeli Beras sebanyak 5 Kg (B2) dengan harga Rp14.000 per Kg (C2).',
    objective: 'Hitung subtotal belanja beras pada sel D2 dengan rumus perkalian =B2*C2.',
    targetCell: 'D2',
    targetRowNumber: 2,
    targetColKey: 'subtotal',
    targetColLetter: 'D',
    columns: [
      { key: 'barang', label: 'Nama Barang', letter: 'A' },
      { key: 'jumlah', label: 'Jumlah (Kg)', letter: 'B' },
      { key: 'harga', label: 'Harga Satuan (Rp)', letter: 'C' },
      { key: 'subtotal', label: 'Subtotal (Rp)', letter: 'D' },
    ],
    rows: [
      { rowNumber: 2, values: { barang: 'Beras Rojolele', jumlah: 5, harga: 14000, subtotal: '?' } },
      { rowNumber: 3, values: { barang: 'Minyak Goreng', jumlah: 2, harga: 16000, subtotal: 32000 } },
    ],
    validFormulas: ['=B2*C2', '=C2*B2', '=PRODUCT(B2:C2)', '=PRODUCT(B2,C2)'],
    acceptedAnswers: [70000],
    hints: ['Di Excel perkalian memakai bintang (*). Ketik =B2*C2.'],
    explanation: '5 Kg x Rp14.000 = Rp70.000.',
    samplePlaceholder: '=B2*C2',
    theory: {
      concept: 'Gunakan tanda bintang (*) untuk perkalian.',
      whyItMatters: 'Digunakan di setiap baris invoice kasir dan daftar belanja.',
      syntax: '=sel1 * sel2',
      example: '=B2 * C2',
    },
  },
  {
    id: 4,
    chapterId: 1,
    title: 'Modul 4: Pembagian Tagihan / Split Bill (/)',
    category: 'Aritmatika',
    difficulty: 'Pemula',
    scenario: 'Makan malam bersama 5 orang (C2) dengan total tagihan Rp250.000 (B2).',
    objective: 'Hitung biaya per orang pada sel D2 dengan membagi Total Tagihan (B2) dengan Jumlah Orang (C2).',
    targetCell: 'D2',
    targetRowNumber: 2,
    targetColKey: 'perOrang',
    targetColLetter: 'D',
    columns: [
      { key: 'acara', label: 'Kegiatan', letter: 'A' },
      { key: 'tagihan', label: 'Total Tagihan (Rp)', letter: 'B' },
      { key: 'orang', label: 'Jumlah Orang', letter: 'C' },
      { key: 'perOrang', label: 'Bayar Per Orang (Rp)', letter: 'D' },
    ],
    rows: [
      { rowNumber: 2, values: { acara: 'Makan Malam', tagihan: 250000, orang: 5, perOrang: '?' } },
      { rowNumber: 3, values: { acara: 'Sewa Futsal', tagihan: 180000, orang: 6, perOrang: 30000 } },
    ],
    validFormulas: ['=B2/C2'],
    acceptedAnswers: [50000],
    hints: ['Gunakan garis miring (/). Ketik =B2/C2.'],
    explanation: 'Rp250.000 / 5 orang = Rp50.000.',
    samplePlaceholder: '=B2/C2',
    theory: {
      concept: 'Simbol garis miring (/) adalah operator pembagian di Excel.',
      whyItMatters: 'Menghitung rata-rata manual, rasio per porsi, atau porsi pembagian biaya.',
      syntax: '=sel1 / sel2',
      example: '=B2 / C2',
    },
  },
  {
    id: 5,
    chapterId: 1,
    title: 'Modul 5: Menghitung Persentase Diskon (%)',
    category: 'Aritmatika',
    difficulty: 'Pemula',
    scenario: 'Baju seharga Rp200.000 (B2) mendapatkan diskon sebesar 20% (C2). Hitung nominal potongan harganya.',
    objective: 'Hitung potongan harga pada sel D2 dengan mengalikan Harga Asli (B2) dengan Persentase Diskon (C2).',
    targetCell: 'D2',
    targetRowNumber: 2,
    targetColKey: 'potongan',
    targetColLetter: 'D',
    columns: [
      { key: 'item', label: 'Nama Pakaian', letter: 'A' },
      { key: 'harga', label: 'Harga Asli (Rp)', letter: 'B' },
      { key: 'diskon', label: 'Diskon (%)', letter: 'C' },
      { key: 'potongan', label: 'Potongan Diskon (Rp)', letter: 'D' },
    ],
    rows: [
      { rowNumber: 2, values: { item: 'Kemeja Polos', harga: 200000, diskon: '20%', potongan: '?' } },
      { rowNumber: 3, values: { item: 'Celana Chino', harga: 250000, diskon: '10%', potongan: 25000 } },
    ],
    validFormulas: ['=B2*C2', '=B2*20%', '=B2*0.2'],
    acceptedAnswers: [40000],
    hints: ['Ketik =B2*C2 atau =B2*20%.'],
    explanation: 'Rp200.000 x 20% = Rp40.000.',
    samplePlaceholder: '=B2*C2',
    theory: {
      concept: 'Di Excel simbol % otomatis diartikan sebagai per 100 (contoh 20% = 0.2).',
      whyItMatters: 'Kerap digunakan untuk kalkulasi pajak PPN, diskon promo, dan margin profit.',
      syntax: '=sel_harga * sel_persen',
      example: '=B2 * C2',
    },
  },
  {
    id: 6,
    chapterId: 1,
    title: 'Modul 6: Hirarki Tanda Kurung Aritmatika ()',
    category: 'Aritmatika',
    difficulty: 'Pemula',
    scenario: 'Kamu membeli 2 baju seharga Rp100.000 (B2) dan 1 celana seharga Rp150.000 (C2), lalu semua total pembelian dikenakan diskon 10% (D2).',
    objective: 'Hitung total bayar akhir setelah diskon pada sel E2 dengan rumus =(B2+C2)*(1-D2).',
    targetCell: 'E2',
    targetRowNumber: 2,
    targetColKey: 'bayar',
    targetColLetter: 'E',
    columns: [
      { key: 'ket', label: 'Paket Belanja', letter: 'A' },
      { key: 'baju', label: 'Baju (Rp)', letter: 'B' },
      { key: 'celana', label: 'Celana (Rp)', letter: 'C' },
      { key: 'diskon', label: 'Diskon', letter: 'D' },
      { key: 'bayar', label: 'Total Bayar (Rp)', letter: 'E' },
    ],
    rows: [
      { rowNumber: 2, values: { ket: 'Paket Promo', baju: 100000, celana: 150000, diskon: '10%', bayar: '?' } },
    ],
    validFormulas: ['=(B2+C2)*(1-D2)', '=(B2+C2)*0.9', '=(B2+C2)*90%'],
    acceptedAnswers: [225000],
    hints: ['Gunakan kurung: =(B2+C2)*(1-D2)'],
    explanation: '(Rp100.000 + Rp150.000) x 90% = Rp225.000.',
    samplePlaceholder: '=(B2+C2)*(1-D2)',
    theory: {
      concept: 'Operasi di dalam kurung () selalu dikerjakan lebih dulu sebelum perkalian/pembagian.',
      whyItMatters: 'Mencegah kesalahan fatal dalam perhitungan keuangan multi-tahap.',
      syntax: '=(sel1 + sel2) * faktor',
      example: '=(B2 + C2) * (1 - D2)',
    },
  },

  // ========================================================
  // BAB 2: AGREGASI & STATISTIK ESENSIAL (Modul 7 - 14)
  // ========================================================
  {
    id: 7,
    chapterId: 2,
    title: 'Modul 7: Penjumlahan Cepat (SUM)',
    category: 'Agregasi',
    difficulty: 'Pemula',
    scenario: 'Menghitung total seluruh anggaran bulanan anak kost dari baris C2 sampai C6.',
    objective: 'Hitung total anggaran pada sel C7 menggunakan rumus =SUM(C2:C6).',
    targetCell: 'C7',
    targetRowNumber: 7,
    targetColKey: 'biaya',
    targetColLetter: 'C',
    columns: [
      { key: 'no', label: 'No', letter: 'A' },
      { key: 'pos', label: 'Pos Kebutuhan', letter: 'B' },
      { key: 'biaya', label: 'Anggaran (Rp)', letter: 'C' },
    ],
    rows: [
      { rowNumber: 2, values: { no: 1, pos: 'Sewa Kost', biaya: 900000 } },
      { rowNumber: 3, values: { no: 2, pos: 'Makan & Minum', biaya: 1000000 } },
      { rowNumber: 4, values: { no: 3, pos: 'Token Listrik', biaya: 150000 } },
      { rowNumber: 5, values: { no: 4, pos: 'Paket Internet', biaya: 150000 } },
      { rowNumber: 6, values: { no: 5, pos: 'Bensin Motor', biaya: 300000 } },
    ],
    totalLabelRow: { label: 'Total Anggaran:', colSpan: 2 },
    validFormulas: ['=SUM(C2:C6)', '=SUM(C2,C3,C4,C5,C6)'],
    acceptedAnswers: [2500000],
    hints: ['Ketik =SUM(C2:C6) lalu tekan Enter.'],
    explanation: 'Total penjumlahan seluruh anggaran = Rp2.500.000.',
    samplePlaceholder: '=SUM(C2:C6)',
    theory: {
      concept: 'Fungsi SUM menjumlahkan rentang nilai sekaligus.',
      whyItMatters: 'Fungsi paling banyak dipakai di dunia kerja.',
      syntax: '=SUM(rentang_sel)',
      example: '=SUM(C2:C6)',
    },
  },
  {
    id: 8,
    chapterId: 2,
    title: 'Modul 8: Nilai Rata-Rata (AVERAGE)',
    category: 'Statistik',
    difficulty: 'Pemula',
    scenario: 'Menghitung nilai rata-rata ujian siswa dari 4 mata pelajaran (C2:C5).',
    objective: 'Hitung nilai rata-rata pada sel C6 menggunakan rumus =AVERAGE(C2:C5).',
    targetCell: 'C6',
    targetRowNumber: 6,
    targetColKey: 'nilai',
    targetColLetter: 'C',
    columns: [
      { key: 'no', label: 'No', letter: 'A' },
      { key: 'mapel', label: 'Mata Pelajaran', letter: 'B' },
      { key: 'nilai', label: 'Nilai Ujian', letter: 'C' },
    ],
    rows: [
      { rowNumber: 2, values: { no: 1, mapel: 'Matematika', nilai: 80 } },
      { rowNumber: 3, values: { no: 2, mapel: 'B. Indonesia', nilai: 90 } },
      { rowNumber: 4, values: { no: 3, mapel: 'IPA', nilai: 85 } },
      { rowNumber: 5, values: { no: 4, mapel: 'B. Inggris', nilai: 85 } },
    ],
    totalLabelRow: { label: 'Rata-Rata Rapor:', colSpan: 2 },
    validFormulas: ['=AVERAGE(C2:C5)', '=AVERAGE(C2,C3,C4,C5)'],
    acceptedAnswers: [85],
    hints: ['Ketik =AVERAGE(C2:C5).'],
    explanation: '(80 + 90 + 85 + 85) / 4 = 85.',
    samplePlaceholder: '=AVERAGE(C2:C5)',
    theory: {
      concept: 'Fungsi AVERAGE menghitung nilai rata-rata numerik.',
      whyItMatters: 'Melihat performa nilai rata-rata atau rata-rata penjualan.',
      syntax: '=AVERAGE(rentang_sel)',
      example: '=AVERAGE(C2:C5)',
    },
  },
  {
    id: 9,
    chapterId: 2,
    title: 'Modul 9: Nilai Tertinggi & Terendah (MAX & MIN)',
    category: 'Statistik',
    difficulty: 'Pemula',
    scenario: 'Mencari tagihan listrik termahal selama 6 bulan terakhir dari sel B2:B7.',
    objective: 'Cari tagihan tertinggi pada sel B8 menggunakan rumus =MAX(B2:B7).',
    targetCell: 'B8',
    targetRowNumber: 8,
    targetColKey: 'tagihan',
    targetColLetter: 'B',
    columns: [
      { key: 'bulan', label: 'Bulan', letter: 'A' },
      { key: 'tagihan', label: 'Tagihan Listrik (Rp)', letter: 'B' },
    ],
    rows: [
      { rowNumber: 2, values: { bulan: 'Januari', tagihan: 180000 } },
      { rowNumber: 3, values: { bulan: 'Februari', tagihan: 210000 } },
      { rowNumber: 4, values: { bulan: 'Maret', tagihan: 350000 } },
      { rowNumber: 5, values: { bulan: 'April', tagihan: 195000 } },
      { rowNumber: 6, values: { bulan: 'Mei', tagihan: 240000 } },
      { rowNumber: 7, values: { bulan: 'Juni', tagihan: 220000 } },
    ],
    totalLabelRow: { label: 'Tagihan Termahal:', colSpan: 1 },
    validFormulas: ['=MAX(B2:B7)'],
    acceptedAnswers: [350000],
    hints: ['Ketik =MAX(B2:B7).'],
    explanation: 'Tagihan tertinggi adalah Rp350.000 pada bulan Maret.',
    samplePlaceholder: '=MAX(B2:B7)',
    theory: {
      concept: 'MAX mencari nilai terbesar, MIN mencari nilai terkecil.',
      whyItMatters: 'Mengetahui rekor puncak dan pengeluaran terendah.',
      syntax: '=MAX(rentang_sel)',
      example: '=MAX(B2:B7)',
    },
  },
  {
    id: 10,
    chapterId: 2,
    title: 'Modul 10: Menghitung Data Angka (COUNT)',
    category: 'Statistik',
    difficulty: 'Pemula',
    scenario: 'Menghitung berapa banyak siswa yang SUDAH memiliki nilai ujian angka pada kolom C.',
    objective: 'Hitung jumlah sel yang berisi angka pada sel C7 menggunakan rumus =COUNT(C2:C6).',
    targetCell: 'C7',
    targetRowNumber: 7,
    targetColKey: 'skor',
    targetColLetter: 'C',
    columns: [
      { key: 'no', label: 'No', letter: 'A' },
      { key: 'nama', label: 'Nama Siswa', letter: 'B' },
      { key: 'skor', label: 'Skor Ujian', letter: 'C' },
    ],
    rows: [
      { rowNumber: 2, values: { no: 1, nama: 'Budi Santoso', skor: 85 } },
      { rowNumber: 3, values: { no: 2, nama: 'Siti Rahma', skor: 90 } },
      { rowNumber: 4, values: { no: 3, nama: 'Andi Wijaya', skor: 'Susulan' } },
      { rowNumber: 5, values: { no: 4, nama: 'Dewi Lestari', skor: 78 } },
      { rowNumber: 6, values: { no: 5, nama: 'Eko Prasetyo', skor: 88 } },
    ],
    totalLabelRow: { label: 'Total yang Sudah Bernilai:', colSpan: 2 },
    validFormulas: ['=COUNT(C2:C6)'],
    acceptedAnswers: [4],
    hints: ['Fungsi COUNT hanya menghitung angka. Ketik =COUNT(C2:C6).'],
    explanation: 'Dari 5 siswa, ada 4 yang nilainya berupa angka.',
    samplePlaceholder: '=COUNT(C2:C6)',
    theory: {
      concept: 'COUNT hanya menghitung sel berformat angka, mengabaikan teks.',
      whyItMatters: 'Memisahkan data terisi numerik dari keterangan teks.',
      syntax: '=COUNT(rentang)',
      example: '=COUNT(C2:C6)',
    },
  },
  {
    id: 11,
    chapterId: 2,
    title: 'Modul 11: Menghitung Data Teks & Terisi (COUNTA)',
    category: 'Statistik',
    difficulty: 'Pemula',
    scenario: 'Menghitung total seluruh nama peserta yang terdaftar pada absensi di kolom B (B2:B6).',
    objective: 'Hitung total peserta terdaftar pada sel B7 menggunakan rumus =COUNTA(B2:B6).',
    targetCell: 'B7',
    targetRowNumber: 7,
    targetColKey: 'nama',
    targetColLetter: 'B',
    columns: [
      { key: 'no', label: 'No', letter: 'A' },
      { key: 'nama', label: 'Nama Peserta', letter: 'B' },
      { key: 'kota', label: 'Kota', letter: 'C' },
    ],
    rows: [
      { rowNumber: 2, values: { no: 1, nama: 'Ahmad Dahlan', kota: 'Yogyakarta' } },
      { rowNumber: 3, values: { no: 2, nama: 'Rini Susanti', kota: 'Surabaya' } },
      { rowNumber: 4, values: { no: 3, nama: 'Fajar Hidayat', kota: 'Bandung' } },
      { rowNumber: 5, values: { no: 4, nama: 'Dewi Lestari', kota: 'Jakarta' } },
      { rowNumber: 6, values: { no: 5, nama: 'Dimas Anggara', kota: 'Semarang' } },
    ],
    totalLabelRow: { label: 'Total Peserta Terdaftar:', colSpan: 1 },
    validFormulas: ['=COUNTA(B2:B6)'],
    acceptedAnswers: [5],
    hints: ['Gunakan =COUNTA(B2:B6) untuk menghitung sel teks non-kosong.'],
    explanation: 'Ada 5 peserta yang terdaftar.',
    samplePlaceholder: '=COUNTA(B2:B6)',
    theory: {
      concept: 'COUNTA (Count All) menghitung semua sel yang tidak kosong (baik teks maupun angka).',
      whyItMatters: 'Menghitung daftar nama, nomor resi, dan presensi.',
      syntax: '=COUNTA(rentang)',
      example: '=COUNTA(B2:B6)',
    },
  },
  {
    id: 12,
    chapterId: 2,
    title: 'Modul 12: Menghitung Data Kosong (COUNTBLANK)',
    category: 'Statistik',
    difficulty: 'Pemula',
    scenario: 'Mengecek berapa banyak kolom tugas siswa yang MASIH KOSONG (belum mengumpulkan tugas) pada sel C2:C6.',
    objective: 'Hitung jumlah sel kosong pada sel C7 menggunakan rumus =COUNTBLANK(C2:C6).',
    targetCell: 'C7',
    targetRowNumber: 7,
    targetColKey: 'tugas',
    targetColLetter: 'C',
    columns: [
      { key: 'no', label: 'No', letter: 'A' },
      { key: 'nama', label: 'Nama Siswa', letter: 'B' },
      { key: 'tugas', label: 'Status Pengumpulan', letter: 'C' },
    ],
    rows: [
      { rowNumber: 2, values: { no: 1, nama: 'Budi Santoso', tugas: 'Sudah' } },
      { rowNumber: 3, values: { no: 2, nama: 'Siti Rahma', tugas: '' } },
      { rowNumber: 4, values: { no: 3, nama: 'Andi Wijaya', tugas: 'Sudah' } },
      { rowNumber: 5, values: { no: 4, nama: 'Dewi Lestari', tugas: '' } },
      { rowNumber: 6, values: { no: 5, nama: 'Eko Prasetyo', tugas: 'Sudah' } },
    ],
    totalLabelRow: { label: 'Jumlah yang Belum Kumpul:', colSpan: 2 },
    validFormulas: ['=COUNTBLANK(C2:C6)'],
    acceptedAnswers: [2],
    hints: ['Ketik =COUNTBLANK(C2:C6).'],
    explanation: 'Terdapat 2 siswa yang belum mengumpulkan tugas (sel kosong).',
    samplePlaceholder: '=COUNTBLANK(C2:C6)',
    theory: {
      concept: 'COUNTBLANK menghitung jumlah sel yang benar-benar kosong.',
      whyItMatters: 'Audit kelengkapan formulir dan data yang belum diinput.',
      syntax: '=COUNTBLANK(rentang)',
      example: '=COUNTBLANK(C2:C6)',
    },
  },
  {
    id: 13,
    chapterId: 2,
    title: 'Modul 13: Nilai Terbesar ke-N (LARGE)',
    category: 'Statistik',
    difficulty: 'Menengah',
    scenario: 'Menentukan Juara 2 (Skor tertinggi ke-2) dari kompetisi matematika pada sel C2:C6.',
    objective: 'Cari skor tertinggi ke-2 pada sel C7 menggunakan rumus =LARGE(C2:C6, 2).',
    targetCell: 'C7',
    targetRowNumber: 7,
    targetColKey: 'skor',
    targetColLetter: 'C',
    columns: [
      { key: 'no', label: 'No', letter: 'A' },
      { key: 'nama', label: 'Nama Peserta', letter: 'B' },
      { key: 'skor', label: 'Skor Akhir', letter: 'C' },
    ],
    rows: [
      { rowNumber: 2, values: { no: 1, nama: 'Budi Santoso', skor: 82 } },
      { rowNumber: 3, values: { no: 2, nama: 'Siti Rahma', skor: 98 } },
      { rowNumber: 4, values: { no: 3, nama: 'Andi Wijaya', skor: 91 } },
      { rowNumber: 5, values: { no: 4, nama: 'Dewi Lestari', skor: 75 } },
      { rowNumber: 6, values: { no: 5, nama: 'Eko Prasetyo', skor: 88 } },
    ],
    totalLabelRow: { label: 'Skor Juara 2 (Tertinggi ke-2):', colSpan: 2 },
    validFormulas: ['=LARGE(C2:C6, 2)', '=LARGE(C2:C6,2)'],
    acceptedAnswers: [91],
    hints: ['Format: =LARGE(rentang, ranking). Ketik =LARGE(C2:C6, 2).'],
    explanation: 'Skor tertinggi #1 adalah 98 (Siti), tertinggi #2 adalah 91 (Andi).',
    samplePlaceholder: '=LARGE(C2:C6, 2)',
    theory: {
      concept: 'Fungsi LARGE(rentang, k) mencari nilai terbesar peringkat ke-k.',
      whyItMatters: 'Mencari runner up, top 3 sales, atau omset kedua terbesar.',
      syntax: '=LARGE(rentang, k)',
      example: '=LARGE(C2:C6, 2)',
    },
  },
  {
    id: 14,
    chapterId: 2,
    title: 'Modul 14: Nilai Terkecil ke-N (SMALL)',
    category: 'Statistik',
    difficulty: 'Menengah',
    scenario: 'Mencari waktu tempuh pelari tercepat ke-2 (waktu terkecil ke-2 dalam detik) pada sel C2:C5.',
    objective: 'Cari waktu tercepat ke-2 pada sel C6 menggunakan rumus =SMALL(C2:C5, 2).',
    targetCell: 'C6',
    targetRowNumber: 6,
    targetColKey: 'detik',
    targetColLetter: 'C',
    columns: [
      { key: 'no', label: 'No', letter: 'A' },
      { key: 'nama', label: 'Nama Pelari', letter: 'B' },
      { key: 'detik', label: 'Waktu Tempuh (Detik)', letter: 'C' },
    ],
    rows: [
      { rowNumber: 2, values: { no: 1, nama: 'Rian Pratama', detik: 12.4 } },
      { rowNumber: 3, values: { no: 2, nama: 'Fajar Nugraha', detik: 11.2 } },
      { rowNumber: 4, values: { no: 3, nama: 'Dimas Anggara', detik: 11.8 } },
      { rowNumber: 5, values: { no: 4, nama: 'Bambang', detik: 13.1 } },
    ],
    totalLabelRow: { label: 'Tercepat ke-2 (Detik):', colSpan: 2 },
    validFormulas: ['=SMALL(C2:C5, 2)', '=SMALL(C2:C5,2)'],
    acceptedAnswers: [11.8],
    hints: ['Ketik =SMALL(C2:C5, 2).'],
    explanation: 'Waktu tercepat ke-1 adalah 11.2, tercepat ke-2 adalah 11.8 detik.',
    samplePlaceholder: '=SMALL(C2:C5, 2)',
    theory: {
      concept: 'SMALL(rentang, k) mencari nilai terkecil ke-k.',
      whyItMatters: 'Mencari biaya termurah ke-2, ranking waktu tercepat perlombaan.',
      syntax: '=SMALL(rentang, k)',
      example: '=SMALL(C2:C5, 2)',
    },
  },

  // ========================================================
  // BAB 3: MANIPULASI TEKS & STRING (Modul 15 - 22)
  // ========================================================
  {
    id: 15,
    chapterId: 3,
    title: 'Modul 15: Merapikan Huruf Kapital (PROPER)',
    category: 'Teks',
    difficulty: 'Pemula',
    scenario: 'Formulir menghasilkan nama huruf kecil "budi santoso" pada sel A2. Rapikan formatnya.',
    objective: 'Ubah nama pada sel A2 menjadi format rapi berkapital awal pada sel B2 menggunakan =PROPER(A2).',
    targetCell: 'B2',
    targetRowNumber: 2,
    targetColKey: 'rapi',
    targetColLetter: 'B',
    columns: [
      { key: 'mentah', label: 'Nama Mentah', letter: 'A' },
      { key: 'rapi', label: 'Nama Rapi (Hasil)', letter: 'B' },
    ],
    rows: [
      { rowNumber: 2, values: { mentah: 'budi santoso', rapi: '?' } },
      { rowNumber: 3, values: { mentah: 'SITI RAHMAWATI', rapi: 'Siti Rahmawati' } },
    ],
    validFormulas: ['=PROPER(A2)'],
    acceptedAnswers: ['Budi Santoso'],
    hints: ['Ketik =PROPER(A2).'],
    explanation: 'Mengubah "budi santoso" menjadi "Budi Santoso".',
    samplePlaceholder: '=PROPER(A2)',
    theory: {
      concept: 'PROPER membuat huruf awal setiap kata kapital.',
      whyItMatters: 'Membersihkan data input pelanggan dan nama karyawan.',
      syntax: '=PROPER(sel)',
      example: '=PROPER(A2)',
    },
  },
  {
    id: 16,
    chapterId: 3,
    title: 'Modul 16: Huruf Kapital Semua (UPPER)',
    category: 'Teks',
    difficulty: 'Pemula',
    scenario: 'Kode produk pada sel A2 masih bertuliskan huruf kecil "bju-01". Standarkan menjadi huruf besar.',
    objective: 'Ubah kode pada sel A2 menjadi kapital semua pada sel B2 menggunakan =UPPER(A2).',
    targetCell: 'B2',
    targetRowNumber: 2,
    targetColKey: 'hasil',
    targetColLetter: 'B',
    columns: [
      { key: 'kode', label: 'Kode Produk', letter: 'A' },
      { key: 'hasil', label: 'Kode Standar (Kapital)', letter: 'B' },
    ],
    rows: [
      { rowNumber: 2, values: { kode: 'bju-01', hasil: '?' } },
      { rowNumber: 3, values: { kode: 'cln-02', hasil: 'CLN-02' } },
    ],
    validFormulas: ['=UPPER(A2)'],
    acceptedAnswers: ['BJU-01'],
    hints: ['Ketik =UPPER(A2).'],
    explanation: 'Mengubah "bju-01" menjadi "BJU-01".',
    samplePlaceholder: '=UPPER(A2)',
    theory: {
      concept: 'UPPER mengubah semua huruf menjadi huruf besar (kapital).',
      whyItMatters: 'Standardisasi plat nomor, kode invoice, dan NIK.',
      syntax: '=UPPER(sel)',
      example: '=UPPER(A2)',
    },
  },
  {
    id: 17,
    chapterId: 3,
    title: 'Modul 17: Menggabungkan Teks dengan Simbol &',
    category: 'Teks',
    difficulty: 'Pemula',
    scenario: 'Nama Depan ada di sel A2 ("Ahmad") dan Nama Belakang di sel B2 ("Dahlan"). Gabungkan dengan spasi.',
    objective: 'Buat nama lengkap pada sel C2 menggunakan rumus =A2 & " " & B2.',
    targetCell: 'C2',
    targetRowNumber: 2,
    targetColKey: 'lengkap',
    targetColLetter: 'C',
    columns: [
      { key: 'depan', label: 'Nama Depan', letter: 'A' },
      { key: 'belakang', label: 'Nama Belakang', letter: 'B' },
      { key: 'lengkap', label: 'Nama Lengkap', letter: 'C' },
    ],
    rows: [
      { rowNumber: 2, values: { depan: 'Ahmad', belakang: 'Dahlan', lengkap: '?' } },
      { rowNumber: 3, values: { depan: 'Rini', belakang: 'Susanti', lengkap: 'Rini Susanti' } },
    ],
    validFormulas: ['=A2&" "&B2', '=A2 & " " & B2', '=CONCAT(A2, " ", B2)'],
    acceptedAnswers: ['Ahmad Dahlan'],
    hints: ['Ketik =A2 & " " & B2.'],
    explanation: 'Menggabungkan Ahmad + spasi + Dahlan = Ahmad Dahlan.',
    samplePlaceholder: '=A2 & " " & B2',
    theory: {
      concept: 'Simbol & menggabungkan dua string. Beri " " untuk spasi.',
      whyItMatters: 'Menyatukan alamat, nama lengkap, atau kode custom.',
      syntax: '=sel1 & " " & sel2',
      example: '=A2 & " " & B2',
    },
  },
  {
    id: 18,
    chapterId: 3,
    title: 'Modul 18: Menggabungkan Rentang Teks (CONCAT)',
    category: 'Teks',
    difficulty: 'Menengah',
    scenario: 'Menggabungkan kode wilayah (A2), nomor cabang (B2), dan seri (C2) menjadi Kode Barcode Utuh.',
    objective: 'Gabungkan sel A2, B2, dan C2 pada sel D2 menggunakan fungsi =CONCAT(A2, "-", B2, "-", C2).',
    targetCell: 'D2',
    targetRowNumber: 2,
    targetColKey: 'barcode',
    targetColLetter: 'D',
    columns: [
      { key: 'wilayah', label: 'Wilayah', letter: 'A' },
      { key: 'cabang', label: 'Cabang', letter: 'B' },
      { key: 'seri', label: 'Seri', letter: 'C' },
      { key: 'barcode', label: 'Kode Barcode', letter: 'D' },
    ],
    rows: [
      { rowNumber: 2, values: { wilayah: 'JKT', cabang: '01', seri: '99', barcode: '?' } },
    ],
    validFormulas: [
      '=CONCAT(A2,"-",B2,"-",C2)',
      '=CONCAT(A2, "-", B2, "-", C2)',
      '=A2&"-"&B2&"-"&C2',
      '=A2 & "-" & B2 & "-" & C2',
    ],
    acceptedAnswers: ['JKT-01-99'],
    hints: ['Ketik =CONCAT(A2, "-", B2, "-", C2) atau =A2 & "-" & B2 & "-" & C2.'],
    explanation: 'Hasil barcode utuh: JKT-01-99.',
    samplePlaceholder: '=CONCAT(A2, "-", B2, "-", C2)',
    theory: {
      concept: 'Fungsi CONCAT menggabungkan banyak argumen teks.',
      whyItMatters: 'Membuat format serial number dan kode inventaris.',
      syntax: '=CONCAT(teks1, teks2, ...)',
      example: '=CONCAT(A2, "-", B2)',
    },
  },
  {
    id: 19,
    chapterId: 3,
    title: 'Modul 19: Ekstraksi Karakter Kiri (LEFT)',
    category: 'Teks',
    difficulty: 'Menengah',
    scenario: 'Dari ID Anggota "JKT-0891" pada sel A2, ambil 3 karakter pertama ("JKT") sebagai kode kota.',
    objective: 'Ambil 3 karakter pertama pada sel B2 menggunakan rumus =LEFT(A2, 3).',
    targetCell: 'B2',
    targetRowNumber: 2,
    targetColKey: 'kota',
    targetColLetter: 'B',
    columns: [
      { key: 'id', label: 'ID Anggota', letter: 'A' },
      { key: 'kota', label: 'Kode Kota', letter: 'B' },
    ],
    rows: [
      { rowNumber: 2, values: { id: 'JKT-0891', kota: '?' } },
      { rowNumber: 3, values: { id: 'BDG-0122', kota: 'BDG' } },
    ],
    validFormulas: ['=LEFT(A2, 3)', '=LEFT(A2,3)'],
    acceptedAnswers: ['JKT'],
    hints: ['Ketik =LEFT(A2, 3).'],
    explanation: 'Mengambil 3 huruf paling kiri dari "JKT-0891" yaitu "JKT".',
    samplePlaceholder: '=LEFT(A2, 3)',
    theory: {
      concept: 'LEFT(sel, n) mengambil n karakter dari kiri.',
      whyItMatters: 'Memisahkan kode prefiks, tahun dari NIK, atau inisial.',
      syntax: '=LEFT(sel, jumlah_karakter)',
      example: '=LEFT(A2, 3)',
    },
  },
  {
    id: 20,
    chapterId: 3,
    title: 'Modul 20: Ekstraksi Karakter Kanan (RIGHT)',
    category: 'Teks',
    difficulty: 'Menengah',
    scenario: 'Dari Nomor Invoice "INV-2026-889" pada sel A2, ambil 3 digit terakhir ("889") sebagai nomor urut.',
    objective: 'Ambil 3 digit terakhir pada sel B2 menggunakan rumus =RIGHT(A2, 3).',
    targetCell: 'B2',
    targetRowNumber: 2,
    targetColKey: 'urut',
    targetColLetter: 'B',
    columns: [
      { key: 'inv', label: 'No Invoice', letter: 'A' },
      { key: 'urut', label: 'No Urut (3 Digit)', letter: 'B' },
    ],
    rows: [
      { rowNumber: 2, values: { inv: 'INV-2026-889', urut: '?' } },
      { rowNumber: 3, values: { inv: 'INV-2026-120', urut: '120' } },
    ],
    validFormulas: ['=RIGHT(A2, 3)', '=RIGHT(A2,3)'],
    acceptedAnswers: ['889'],
    hints: ['Ketik =RIGHT(A2, 3).'],
    explanation: 'Mengambil 3 digit paling kanan dari invoice = "889".',
    samplePlaceholder: '=RIGHT(A2, 3)',
    theory: {
      concept: 'RIGHT(sel, n) mengambil n karakter dari sisi paling kanan.',
      whyItMatters: 'Mengambil ekstensi file, digit nomor antrian, atau sufiks.',
      syntax: '=RIGHT(sel, jumlah_karakter)',
      example: '=RIGHT(A2, 3)',
    },
  },
  {
    id: 21,
    chapterId: 3,
    title: 'Modul 21: Ekstraksi Karakter Tengah (MID)',
    category: 'Teks',
    difficulty: 'Menengah',
    scenario: 'Dari format NIK "3201-2026-99" pada sel A2, ambil tahun "2026" yang dimulai dari karakter ke-6 sebanyak 4 huruf.',
    objective: 'Ambil tahun pada sel B2 menggunakan rumus =MID(A2, 6, 4).',
    targetCell: 'B2',
    targetRowNumber: 2,
    targetColKey: 'tahun',
    targetColLetter: 'B',
    columns: [
      { key: 'nik', label: 'Nomor Registrasi', letter: 'A' },
      { key: 'tahun', label: 'Tahun Terdaftar', letter: 'B' },
    ],
    rows: [
      { rowNumber: 2, values: { nik: '3201-2026-99', tahun: '?' } },
    ],
    validFormulas: ['=MID(A2, 6, 4)', '=MID(A2,6,4)'],
    acceptedAnswers: ['2026'],
    hints: ['Format MID(sel, posisi_awal, panjang). Ketik =MID(A2, 6, 4).'],
    explanation: 'Mengambil 4 karakter mulai posisi ke-6 = "2026".',
    samplePlaceholder: '=MID(A2, 6, 4)',
    theory: {
      concept: 'MID(sel, start, length) memotong teks dari posisi tengah.',
      whyItMatters: 'Mengekstrak tanggal lahir dari NIK atau kode batch produk.',
      syntax: '=MID(sel, start, length)',
      example: '=MID(A2, 6, 4)',
    },
  },
  {
    id: 22,
    chapterId: 3,
    title: 'Modul 22: Menghapus Spasi Berlebih (TRIM) & Panjang Teks (LEN)',
    category: 'Teks',
    difficulty: 'Menengah',
    scenario: 'Teks pada sel A2 memiliki spasi ganda yang berantakan ("   Belajar   Excel   "). Hapus spasi berlebihnya.',
    objective: 'Bersihkan spasi pada sel B2 menggunakan rumus =TRIM(A2).',
    targetCell: 'B2',
    targetRowNumber: 2,
    targetColKey: 'bersih',
    targetColLetter: 'B',
    columns: [
      { key: 'kotor', label: 'Teks Berantakan', letter: 'A' },
      { key: 'bersih', label: 'Teks Bersih (TRIM)', letter: 'B' },
    ],
    rows: [
      { rowNumber: 2, values: { kotor: '   Belajar   Excel   ', bersih: '?' } },
    ],
    validFormulas: ['=TRIM(A2)'],
    acceptedAnswers: ['Belajar Excel'],
    hints: ['Ketik =TRIM(A2).'],
    explanation: 'TRIM menghapus semua spasi di awal/akhir dan menyisakan satu spasi antar kata.',
    samplePlaceholder: '=TRIM(A2)',
    theory: {
      concept: 'TRIM membersihkan spasi liar, LEN menghitung jumlah karakter.',
      whyItMatters: 'Pencegahan error pencarian VLOOKUP akibat spasi tak terlihat.',
      syntax: '=TRIM(sel)',
      example: '=TRIM(A2)',
    },
  },

  // ========================================================
  // BAB 4: LOGIKA & PENGAMBILAN KEPUTUSAN (Modul 23 - 30)
  // ========================================================
  {
    id: 23,
    chapterId: 4,
    title: 'Modul 23: Percabangan Logika Dasar (IF)',
    category: 'Logika',
    difficulty: 'Menengah',
    scenario: 'KKM Kelulusan adalah 75. Jika nilai siswa (C2) >= 75 berikan status "LULUS", jika tidak "REMIDI".',
    objective: 'Tentukan status kelulusan siswa pada sel D2 menggunakan rumus =IF(C2>=75, "LULUS", "REMIDI").',
    targetCell: 'D2',
    targetRowNumber: 2,
    targetColKey: 'status',
    targetColLetter: 'D',
    columns: [
      { key: 'no', label: 'No', letter: 'A' },
      { key: 'nama', label: 'Nama Siswa', letter: 'B' },
      { key: 'nilai', label: 'Nilai Ujian', letter: 'C' },
      { key: 'status', label: 'Status Kelulusan', letter: 'D' },
    ],
    rows: [
      { rowNumber: 2, values: { no: 1, nama: 'Budi Santoso', nilai: 82, status: '?' } },
      { rowNumber: 3, values: { no: 2, nama: 'Doni Pratama', nilai: 68, status: 'REMIDI' } },
    ],
    validFormulas: [
      '=IF(C2>=75,"LULUS","REMIDI")',
      '=IF(C2>=75, "LULUS", "REMIDI")',
      '=IF(C2<75, "REMIDI", "LULUS")',
    ],
    acceptedAnswers: ['LULUS'],
    hints: ['Ketik =IF(C2>=75, "LULUS", "REMIDI").'],
    explanation: 'Nilai 82 >= 75 maka bernilai TRUE -> "LULUS".',
    samplePlaceholder: '=IF(C2>=75, "LULUS", "REMIDI")',
    theory: {
      concept: 'IF menguji kondisi dan memberikan output berbeda jika benar vs salah.',
      whyItMatters: 'Otomatisasi evaluasi nilai, bonus penjualan, status bayar.',
      syntax: '=IF(kondisi, "benar", "salah")',
      example: '=IF(C2>=75, "LULUS", "REMIDI")',
    },
  },
  {
    id: 24,
    chapterId: 4,
    title: 'Modul 24: Percabangan Bertingkat (Nested IF)',
    category: 'Logika',
    difficulty: 'Lanjutan',
    scenario: 'Predikat nilai: Jika Nilai (C2) >= 85 predikat "A", jika >= 70 "B", selain itu "C".',
    objective: 'Tentukan predikat pada sel D2 menggunakan rumus =IF(C2>=85, "A", IF(C2>=70, "B", "C")).',
    targetCell: 'D2',
    targetRowNumber: 2,
    targetColKey: 'predikat',
    targetColLetter: 'D',
    columns: [
      { key: 'nama', label: 'Nama Siswa', letter: 'A' },
      { key: 'mapel', label: 'Mata Pelajaran', letter: 'B' },
      { key: 'nilai', label: 'Nilai', letter: 'C' },
      { key: 'predikat', label: 'Grade Huruf', letter: 'D' },
    ],
    rows: [
      { rowNumber: 2, values: { nama: 'Rani Safitri', mapel: 'Matematika', nilai: 90, predikat: '?' } },
    ],
    validFormulas: [
      '=IF(C2>=85,"A",IF(C2>=70,"B","C"))',
      '=IF(C2>=85, "A", IF(C2>=70, "B", "C"))',
    ],
    acceptedAnswers: ['A'],
    hints: ['Ketik =IF(C2>=85, "A", IF(C2>=70, "B", "C")).'],
    explanation: 'Karena nilai 90 >= 85, maka menghasilkan grade "A".',
    samplePlaceholder: '=IF(C2>=85, "A", IF(C2>=70, "B", "C"))',
    theory: {
      concept: 'Nested IF memasukkan fungsi IF kedua di dalam argumen value_if_false.',
      whyItMatters: 'Menentukan grading nilai huruf A/B/C/D dan tingkatan komisi.',
      syntax: '=IF(kondisi1, "A", IF(kondisi2, "B", "C"))',
      example: '=IF(C2>=85, "A", IF(C2>=70, "B", "C"))',
    },
  },
  {
    id: 25,
    chapterId: 4,
    title: 'Modul 25: Logika Ganda dengan AND di dalam IF',
    category: 'Logika',
    difficulty: 'Lanjutan',
    scenario: 'Karyawan mendapat bonus jika Kehadiran (B2) >= 90% DAN Penjualan (C2) >= 100 unit.',
    objective: 'Evaluasi bonus pada sel D2 menggunakan rumus =IF(B2>=90, IF(C2>=100, "Bonus", "Tidak"), "Tidak").',
    targetCell: 'D2',
    targetRowNumber: 2,
    targetColKey: 'bonus',
    targetColLetter: 'D',
    columns: [
      { key: 'nama', label: 'Nama Sales', letter: 'A' },
      { key: 'hadir', label: 'Presensi (%)', letter: 'B' },
      { key: 'unit', label: 'Penjualan Unit', letter: 'C' },
      { key: 'bonus', label: 'Status Bonus', letter: 'D' },
    ],
    rows: [
      { rowNumber: 2, values: { nama: 'Fajar Nugraha', hadir: 95, unit: 120, bonus: '?' } },
    ],
    validFormulas: [
      '=IF(B2>=90, IF(C2>=100, "Bonus", "Tidak"), "Tidak")',
      '=IF(B2>=90,IF(C2>=100,"Bonus","Tidak"),"Tidak")',
    ],
    acceptedAnswers: ['Bonus'],
    hints: ['Ketik =IF(B2>=90, IF(C2>=100, "Bonus", "Tidak"), "Tidak").'],
    explanation: 'Presensi 95% (>=90) dan Unit 120 (>=100) keduanya lolos -> "Bonus".',
    samplePlaceholder: '=IF(B2>=90, IF(C2>=100, "Bonus", "Tidak"), "Tidak")',
    theory: {
      concept: 'Menguji dua syarat sekaligus agar bernilai benar.',
      whyItMatters: 'Evaluasi insentif multi-indikator KPI karyawan.',
      syntax: '=IF(syarat1, IF(syarat2, "Ya", "Tidak"), "Tidak")',
      example: '=IF(B2>=90, IF(C2>=100, "Bonus", "Tidak"), "Tidak")',
    },
  },
  {
    id: 26,
    chapterId: 4,
    title: 'Modul 26: Menghitung Bersyarat (COUNTIF)',
    category: 'Logika',
    difficulty: 'Menengah',
    scenario: 'Menghitung berapa banyak siswa yang berstatus "Hadir" dari daftar absensi C2:C6.',
    objective: 'Hitung total siswa hadir pada sel C7 menggunakan rumus =COUNTIF(C2:C6, "Hadir").',
    targetCell: 'C7',
    targetRowNumber: 7,
    targetColKey: 'status',
    targetColLetter: 'C',
    columns: [
      { key: 'no', label: 'No', letter: 'A' },
      { key: 'nama', label: 'Nama Siswa', letter: 'B' },
      { key: 'status', label: 'Status Presensi', letter: 'C' },
    ],
    rows: [
      { rowNumber: 2, values: { no: 1, nama: 'Budi Santoso', status: 'Hadir' } },
      { rowNumber: 3, values: { no: 2, nama: 'Siti Rahma', status: 'Hadir' } },
      { rowNumber: 4, values: { no: 3, nama: 'Andi Wijaya', status: 'Sakit' } },
      { rowNumber: 5, values: { no: 4, nama: 'Dewi Lestari', status: 'Hadir' } },
      { rowNumber: 6, values: { no: 5, nama: 'Eko Prasetyo', status: 'Hadir' } },
    ],
    totalLabelRow: { label: 'Total Hadir:', colSpan: 2 },
    validFormulas: ['=COUNTIF(C2:C6, "Hadir")', '=COUNTIF(C2:C6,"Hadir")'],
    acceptedAnswers: [4],
    hints: ['Ketik =COUNTIF(C2:C6, "Hadir").'],
    explanation: 'Ada 4 siswa yang berstatus Hadir.',
    samplePlaceholder: '=COUNTIF(C2:C6, "Hadir")',
    theory: {
      concept: 'COUNTIF(rentang, "kriteria") menghitung sel yang memenuhi 1 syarat.',
      whyItMatters: 'Menghitung jumlah invoice lunas atau barang lulus QC.',
      syntax: '=COUNTIF(rentang, "kriteria")',
      example: '=COUNTIF(C2:C6, "Hadir")',
    },
  },
  {
    id: 27,
    chapterId: 4,
    title: 'Modul 27: Menjumlahkan Bersyarat (SUMIF)',
    category: 'Logika',
    difficulty: 'Menengah',
    scenario: 'Menghitung total uang pengeluaran khusus untuk kategori "Makanan" dari sel B2:B7 dan C2:C7.',
    objective: 'Hitung total pengeluaran makanan pada sel C8 menggunakan rumus =SUMIF(B2:B7, "Makanan", C2:C7).',
    targetCell: 'C8',
    targetRowNumber: 8,
    targetColKey: 'nominal',
    targetColLetter: 'C',
    columns: [
      { key: 'tgl', label: 'Tanggal', letter: 'A' },
      { key: 'kategori', label: 'Kategori', letter: 'B' },
      { key: 'nominal', label: 'Nominal (Rp)', letter: 'C' },
    ],
    rows: [
      { rowNumber: 2, values: { tgl: '01/08', kategori: 'Makanan', nominal: 25000 } },
      { rowNumber: 3, values: { tgl: '01/08', kategori: 'Transport', nominal: 15000 } },
      { rowNumber: 4, values: { tgl: '02/08', kategori: 'Makanan', nominal: 35000 } },
      { rowNumber: 5, values: { tgl: '02/08', kategori: 'Hiburan', nominal: 50000 } },
      { rowNumber: 6, values: { tgl: '03/08', kategori: 'Makanan', nominal: 35000 } },
      { rowNumber: 7, values: { tgl: '03/08', kategori: 'Transport', nominal: 20000 } },
    ],
    totalLabelRow: { label: 'Total Khusus Makanan:', colSpan: 2 },
    validFormulas: [
      '=SUMIF(B2:B7, "Makanan", C2:C7)',
      '=SUMIF(B2:B7,"Makanan",C2:C7)',
    ],
    acceptedAnswers: [95000],
    hints: ['Ketik =SUMIF(B2:B7, "Makanan", C2:C7).'],
    explanation: 'Total pos makanan: Rp25.000 + Rp35.000 + Rp35.000 = Rp95.000.',
    samplePlaceholder: '=SUMIF(B2:B7, "Makanan", C2:C7)',
    theory: {
      concept: 'SUMIF menjumlahkan angka jika kolom kategorinya cocok dengan syarat.',
      whyItMatters: 'Rekapitulasi keuangan per divisi atau penjualan per produk.',
      syntax: '=SUMIF(range_kategori, "syarat", range_angka)',
      example: '=SUMIF(B2:B7, "Makanan", C2:C7)',
    },
  },
  {
    id: 28,
    chapterId: 4,
    title: 'Modul 28: Rata-Rata Bersyarat (AVERAGEIF)',
    category: 'Logika',
    difficulty: 'Menengah',
    scenario: 'Menghitung rata-rata nilai ujian siswa KHUSUS kelas "IPA" dari kolom B2:B6 dan C2:C6.',
    objective: 'Hitung rata-rata nilai kelas IPA pada sel C7 menggunakan rumus =AVERAGEIF(B2:B6, "IPA", C2:C6).',
    targetCell: 'C7',
    targetRowNumber: 7,
    targetColKey: 'nilai',
    targetColLetter: 'C',
    columns: [
      { key: 'nama', label: 'Nama Siswa', letter: 'A' },
      { key: 'jurusan', label: 'Peminatan', letter: 'B' },
      { key: 'nilai', label: 'Nilai Akhir', letter: 'C' },
    ],
    rows: [
      { rowNumber: 2, values: { nama: 'Budi Santoso', jurusan: 'IPA', nilai: 80 } },
      { rowNumber: 3, values: { nama: 'Siti Rahma', jurusan: 'IPS', nilai: 90 } },
      { rowNumber: 4, values: { nama: 'Andi Wijaya', jurusan: 'IPA', nilai: 90 } },
      { rowNumber: 5, values: { nama: 'Dewi Lestari', jurusan: 'IPS', nilai: 85 } },
      { rowNumber: 6, values: { nama: 'Eko Prasetyo', jurusan: 'IPA', nilai: 85 } },
    ],
    totalLabelRow: { label: 'Rata-Rata Kelas IPA:', colSpan: 2 },
    validFormulas: [
      '=AVERAGEIF(B2:B6, "IPA", C2:C6)',
      '=AVERAGEIF(B2:B6,"IPA",C2:C6)',
    ],
    acceptedAnswers: [85],
    hints: ['Ketik =AVERAGEIF(B2:B6, "IPA", C2:C6).'],
    explanation: 'Nilai IPA: 80, 90, 85 -> Rata-rata = 85.',
    samplePlaceholder: '=AVERAGEIF(B2:B6, "IPA", C2:C6)',
    theory: {
      concept: 'AVERAGEIF menghitung mean dari data yang sesuai kriteria.',
      whyItMatters: 'Menganalisis rata-rata nilai per kelas atau rata-rata belanja segmen pelanggan.',
      syntax: '=AVERAGEIF(range_kategori, "syarat", range_angka)',
      example: '=AVERAGEIF(B2:B6, "IPA", C2:C6)',
    },
  },
  {
    id: 29,
    chapterId: 4,
    title: 'Modul 29: Menghitung Angka di Atas Ambang Batas (COUNTIF Nilai)',
    category: 'Logika',
    difficulty: 'Menengah',
    scenario: 'Menghitung ada berapa siswa yang nilainya di atas atau sama dengan 85 (>=85) pada sel C2:C6.',
    objective: 'Hitung jumlah nilai >=85 pada sel C7 menggunakan rumus =COUNTIF(C2:C6, ">=85").',
    targetCell: 'C7',
    targetRowNumber: 7,
    targetColKey: 'nilai',
    targetColLetter: 'C',
    columns: [
      { key: 'no', label: 'No', letter: 'A' },
      { key: 'nama', label: 'Nama Siswa', letter: 'B' },
      { key: 'nilai', label: 'Skor Ujian', letter: 'C' },
    ],
    rows: [
      { rowNumber: 2, values: { no: 1, nama: 'Budi Santoso', nilai: 80 } },
      { rowNumber: 3, values: { no: 2, nama: 'Siti Rahma', nilai: 95 } },
      { rowNumber: 4, values: { no: 3, nama: 'Andi Wijaya', nilai: 88 } },
      { rowNumber: 5, values: { no: 4, nama: 'Dewi Lestari', nilai: 72 } },
      { rowNumber: 6, values: { no: 5, nama: 'Eko Prasetyo', nilai: 90 } },
    ],
    totalLabelRow: { label: 'Jumlah Siswa Nilai >= 85:', colSpan: 2 },
    validFormulas: ['=COUNTIF(C2:C6, ">=85")', '=COUNTIF(C2:C6,">=85")'],
    acceptedAnswers: [3],
    hints: ['Ketik =COUNTIF(C2:C6, ">=85").'],
    explanation: 'Ada 3 siswa dengan nilai >= 85 (Siti 95, Andi 88, Eko 90).',
    samplePlaceholder: '=COUNTIF(C2:C6, ">=85")',
    theory: {
      concept: 'Kriteria angka pembanding seperti ">=85" harus diapit tanda kutip ganda.',
      whyItMatters: 'Filter performa tinggi dan ambang batas kelulusan.',
      syntax: '=COUNTIF(rentang, ">=angka")',
      example: '=COUNTIF(C2:C6, ">=85")',
    },
  },
  {
    id: 30,
    chapterId: 4,
    title: 'Modul 30: Menjumlahkan Nilai Transaksi Besar (SUMIF Ambang)',
    category: 'Logika',
    difficulty: 'Menengah',
    scenario: 'Menjumlahkan total nominal transaksi yang nilainya di atas Rp100.000 (>=100000) dari sel B2:B6.',
    objective: 'Hitung total transaksi besar pada sel B7 menggunakan rumus =SUMIF(B2:B6, ">=100000").',
    targetCell: 'B7',
    targetRowNumber: 7,
    targetColKey: 'nominal',
    targetColLetter: 'B',
    columns: [
      { key: 'invoice', label: 'No Invoice', letter: 'A' },
      { key: 'nominal', label: 'Nominal Tagihan (Rp)', letter: 'B' },
    ],
    rows: [
      { rowNumber: 2, values: { invoice: 'INV-01', nominal: 50000 } },
      { rowNumber: 3, values: { invoice: 'INV-02', nominal: 150000 } },
      { rowNumber: 4, values: { invoice: 'INV-03', nominal: 75000 } },
      { rowNumber: 5, values: { invoice: 'INV-04', nominal: 200000 } },
      { rowNumber: 6, values: { invoice: 'INV-05', nominal: 120000 } },
    ],
    totalLabelRow: { label: 'Total Transaksi >= Rp100k:', colSpan: 1 },
    validFormulas: ['=SUMIF(B2:B6, ">=100000")', '=SUMIF(B2:B6,">=100000")'],
    acceptedAnswers: [470000],
    hints: ['Ketik =SUMIF(B2:B6, ">=100000").'],
    explanation: 'Transaksi >= 100k: 150.000 + 200.000 + 120.000 = Rp470.000.',
    samplePlaceholder: '=SUMIF(B2:B6, ">=100000")',
    theory: {
      concept: 'SUMIF dengan 2 argumen langsung menjumlahkan sel yang memenuhi kriteria numerik.',
      whyItMatters: 'Menganalisis pendapatan dari klien bernilai tinggi (*high-value clients*).',
      syntax: '=SUMIF(rentang, ">=nilai")',
      example: '=SUMIF(B2:B6, ">=100000")',
    },
  },

  // ========================================================
  // BAB 5: PENCARIAN DATA & LOOKUP (Modul 31 - 36)
  // ========================================================
  {
    id: 31,
    chapterId: 5,
    title: 'Modul 31: Pencarian Harga Kasir (VLOOKUP)',
    category: 'Lookup',
    difficulty: 'Lanjutan',
    scenario: 'Pelanggan membeli Kode Barang "BRG-02" pada sel A2. Tarik Harga Satuan secara otomatis dari tabel referensi master (D2:F4).',
    objective: 'Tarik harga pada sel C2 menggunakan rumus =VLOOKUP(A2, D2:F4, 3, FALSE).',
    targetCell: 'C2',
    targetRowNumber: 2,
    targetColKey: 'harga',
    targetColLetter: 'C',
    columns: [
      { key: 'kode', label: 'Kode Beli', letter: 'A' },
      { key: 'nama', label: 'Nama Barang', letter: 'B' },
      { key: 'harga', label: 'Harga Satuan (Rp)', letter: 'C' },
      { key: 'refKode', label: '[Ref] Kode', letter: 'D' },
      { key: 'refBarang', label: '[Ref] Barang', letter: 'E' },
      { key: 'refHarga', label: '[Ref] Harga', letter: 'F' },
    ],
    rows: [
      { rowNumber: 2, values: { kode: 'BRG-02', nama: 'Gula Pasir 1Kg', harga: '?', refKode: 'BRG-01', refBarang: 'Beras 5Kg', refHarga: 70000 } },
      { rowNumber: 3, values: { kode: 'BRG-01', nama: 'Beras 5Kg', harga: 70000, refKode: 'BRG-02', refBarang: 'Gula Pasir 1Kg', refHarga: 16000 } },
      { rowNumber: 4, values: { kode: 'BRG-03', nama: 'Minyak 2L', harga: 32000, refKode: 'BRG-03', refBarang: 'Minyak 2L', refHarga: 32000 } },
    ],
    validFormulas: [
      '=VLOOKUP(A2, D2:F4, 3, FALSE)',
      '=VLOOKUP(A2,D2:F4,3,FALSE)',
      '=VLOOKUP(A2, D2:F4, 3, 0)',
      '=VLOOKUP(A2,D2:F4,3,0)',
    ],
    acceptedAnswers: [16000],
    hints: ['Ketik =VLOOKUP(A2, D2:F4, 3, FALSE).'],
    explanation: 'Mencari "BRG-02" di tabel D2:F4 dan mengambil nilai kolom ke-3 yaitu Rp16.000.',
    samplePlaceholder: '=VLOOKUP(A2, D2:F4, 3, FALSE)',
    theory: {
      concept: 'VLOOKUP mencari nilai di kolom paling kiri lalu mengambil data kolom ke-N.',
      whyItMatters: 'Keterampilan paling vital dalam tes kerja administrasi dan finance.',
      syntax: '=VLOOKUP(kunci, tabel_ref, index_kolom, FALSE)',
      example: '=VLOOKUP(A2, D2:F4, 3, FALSE)',
    },
  },
  {
    id: 32,
    chapterId: 5,
    title: 'Modul 32: Pencarian Kontak Modern (XLOOKUP)',
    category: 'Lookup',
    difficulty: 'Lanjutan',
    scenario: 'Mencari nomor telepon darurat staf bernama "Siti Rahma" (A2) dari tabel database kontak (D2:D4 dan E2:E4).',
    objective: 'Ambil nomor kontak pada sel B2 menggunakan rumus modern =XLOOKUP(A2, D2:D4, E2:E4).',
    targetCell: 'B2',
    targetRowNumber: 2,
    targetColKey: 'telp',
    targetColLetter: 'B',
    columns: [
      { key: 'cari', label: 'Nama Staf Dicari', letter: 'A' },
      { key: 'telp', label: 'No Telepon', letter: 'B' },
      { key: 'dbId', label: '[DB] ID', letter: 'C' },
      { key: 'dbNama', label: '[DB] Nama', letter: 'D' },
      { key: 'dbKontak', label: '[DB] Nomor Kontak', letter: 'E' },
    ],
    rows: [
      { rowNumber: 2, values: { cari: 'Siti Rahma', telp: '?', dbId: 101, dbNama: 'Budi Santoso', dbKontak: '0812-3456-7890' } },
      { rowNumber: 3, values: { cari: 'Budi Santoso', telp: '0812-3456-7890', dbId: 102, dbNama: 'Siti Rahma', dbKontak: '0819-8765-4321' } },
      { rowNumber: 4, values: { cari: 'Andi Wijaya', telp: '0857-1122-3344', dbId: 103, dbNama: 'Andi Wijaya', dbKontak: '0857-1122-3344' } },
    ],
    validFormulas: [
      '=XLOOKUP(A2, D2:D4, E2:E4)',
      '=XLOOKUP(A2,D2:D4,E2:E4)',
    ],
    acceptedAnswers: ['0819-8765-4321'],
    hints: ['Ketik =XLOOKUP(A2, D2:D4, E2:E4).'],
    explanation: 'Mencocokkan Siti Rahma pada D2:D4 dan mengambil "0819-8765-4321" dari E2:E4.',
    samplePlaceholder: '=XLOOKUP(A2, D2:D4, E2:E4)',
    theory: {
      concept: 'XLOOKUP adalah fungsi modern pengganti VLOOKUP: XLOOKUP(kunci, range_kunci, range_hasil).',
      whyItMatters: 'Lebih fleksibel, tidak error saat tabel bergeser, dan sangat mudah digunakan.',
      syntax: '=XLOOKUP(kunci, range_cari, range_hasil)',
      example: '=XLOOKUP(A2, D2:D4, E2:E4)',
    },
  },
  {
    id: 33,
    chapterId: 5,
    title: 'Modul 33: Pesan Default XLOOKUP [if_not_found]',
    category: 'Lookup',
    difficulty: 'Lanjutan',
    scenario: 'Jika data karyawan tidak ditemukan di database, tampilkan teks "Tidak Ditemukan" alih-alih error #N/A.',
    objective: 'Cari nama A2 pada D2:D3 dan E2:E3 dengan pesan default pada sel B2: =XLOOKUP(A2, D2:D3, E2:E3, "Tidak Ditemukan").',
    targetCell: 'B2',
    targetRowNumber: 2,
    targetColKey: 'hasil',
    targetColLetter: 'B',
    columns: [
      { key: 'nama', label: 'Nama Dicari', letter: 'A' },
      { key: 'hasil', label: 'Status Kontak', letter: 'B' },
      { key: 'dbNama', label: '[DB] Nama', letter: 'D' },
      { key: 'dbHp', label: '[DB] HP', letter: 'E' },
    ],
    rows: [
      { rowNumber: 2, values: { nama: 'Rian Hidayat', hasil: '?', dbNama: 'Budi Santoso', dbHp: '0812-1111' } },
      { rowNumber: 3, values: { nama: 'Siti', hasil: '0819-2222', dbNama: 'Siti', dbHp: '0819-2222' } },
    ],
    validFormulas: [
      '=XLOOKUP(A2, D2:D3, E2:E3, "Tidak Ditemukan")',
      '=XLOOKUP(A2,D2:D3,E2:E3,"Tidak Ditemukan")',
    ],
    acceptedAnswers: ['Tidak Ditemukan'],
    hints: ['Ketik =XLOOKUP(A2, D2:D3, E2:E3, "Tidak Ditemukan").'],
    explanation: 'Karena Rian tidak ada di database, XLOOKUP mengembalikan "Tidak Ditemukan".',
    samplePlaceholder: '=XLOOKUP(A2, D2:D3, E2:E3, "Tidak Ditemukan")',
    theory: {
      concept: 'Argumen ke-4 pada XLOOKUP berfungsi menggantikan IFERROR.',
      whyItMatters: 'Membuat dashboard tampil profesional tanpa pesan error #N/A.',
      syntax: '=XLOOKUP(kunci, range_kunci, range_hasil, "Pesan Jika Tidak Ada")',
      example: '=XLOOKUP(A2, D2:D3, E2:E3, "Tidak Ditemukan")',
    },
  },
  {
    id: 34,
    chapterId: 5,
    title: 'Modul 34: Pencarian Posisi (MATCH)',
    category: 'Lookup',
    difficulty: 'Lanjutan',
    scenario: 'Mengetahui kota "Bandung" berada pada baris urutan ke berapa di daftar rute sel A2:A5.',
    objective: 'Cari posisi kota pada sel B2 menggunakan rumus =MATCH("Bandung", A2:A5, 0).',
    targetCell: 'B2',
    targetRowNumber: 2,
    targetColKey: 'urutan',
    targetColLetter: 'B',
    columns: [
      { key: 'kota', label: 'Daftar Rute Kota', letter: 'A' },
      { key: 'urutan', label: 'Posisi Urutan', letter: 'B' },
    ],
    rows: [
      { rowNumber: 2, values: { kota: 'Jakarta', urutan: '?' } },
      { rowNumber: 3, values: { kota: 'Bogor', urutan: 2 } },
      { rowNumber: 4, values: { kota: 'Bandung', urutan: 3 } },
      { rowNumber: 5, values: { kota: 'Cirebon', urutan: 4 } },
    ],
    validFormulas: ['=MATCH("Bandung", A2:A5, 0)', '=MATCH("Bandung",A2:A5,0)'],
    acceptedAnswers: [3],
    hints: ['Ketik =MATCH("Bandung", A2:A5, 0).'],
    explanation: 'Bandung berada pada posisi baris ke-3 di dalam rentang A2:A5.',
    samplePlaceholder: '=MATCH("Bandung", A2:A5, 0)',
    theory: {
      concept: 'Fungsi MATCH mengembalikan nomor urutan posisi suatu nilai.',
      whyItMatters: 'Komponen vital untuk dipadukan bersama fungsi INDEX.',
      syntax: '=MATCH("nilai", rentang, 0)',
      example: '=MATCH("Bandung", A2:A5, 0)',
    },
  },
  {
    id: 35,
    chapterId: 5,
    title: 'Modul 35: Mengambil Nilai Berdasarkan Posisi (INDEX)',
    category: 'Lookup',
    difficulty: 'Lanjutan',
    scenario: 'Mengambil nama kota pada baris ke-2 dari daftar sel A2:A4 menggunakan fungsi INDEX.',
    objective: 'Ambil data baris ke-2 pada sel B2 menggunakan rumus =INDEX(A2:A4, 2).',
    targetCell: 'B2',
    targetRowNumber: 2,
    targetColKey: 'hasil',
    targetColLetter: 'B',
    columns: [
      { key: 'kota', label: 'Daftar Kota', letter: 'A' },
      { key: 'hasil', label: 'Hasil INDEX Baris ke-2', letter: 'B' },
    ],
    rows: [
      { rowNumber: 2, values: { kota: 'Surabaya', hasil: '?' } },
      { rowNumber: 3, values: { kota: 'Malang', hasil: 'Malang' } },
      { rowNumber: 4, values: { kota: 'Kediri', hasil: 'Kediri' } },
    ],
    validFormulas: ['=INDEX(A2:A4, 2)', '=INDEX(A2:A4,2)'],
    acceptedAnswers: ['Malang'],
    hints: ['Ketik =INDEX(A2:A4, 2).'],
    explanation: 'Baris ke-2 dari A2:A4 adalah "Malang".',
    samplePlaceholder: '=INDEX(A2:A4, 2)',
    theory: {
      concept: 'INDEX(rentang, nomor_baris) mengembalikan isi sel pada baris ke-N.',
      whyItMatters: 'Pondasi sistem pencarian dinamis dua arah.',
      syntax: '=INDEX(rentang, nomor_baris)',
      example: '=INDEX(A2:A4, 2)',
    },
  },
  {
    id: 36,
    chapterId: 5,
    title: 'Modul 36: Kombinasi INDEX & MATCH',
    category: 'Lookup',
    difficulty: 'Lanjutan',
    scenario: 'Mencari Gaji Karyawan bernama "Andi" (A2) dari tabel nama (D2:D4) dan tabel gaji (E2:E4).',
    objective: 'Ambil gaji pada sel B2 menggunakan rumus =INDEX(E2:E4, MATCH(A2, D2:D4, 0)).',
    targetCell: 'B2',
    targetRowNumber: 2,
    targetColKey: 'gaji',
    targetColLetter: 'B',
    columns: [
      { key: 'nama', label: 'Nama Staf', letter: 'A' },
      { key: 'gaji', label: 'Gaji Pokok (Rp)', letter: 'B' },
      { key: 'dbNama', label: '[DB] Nama', letter: 'D' },
      { key: 'dbGaji', label: '[DB] Gaji', letter: 'E' },
    ],
    rows: [
      { rowNumber: 2, values: { nama: 'Andi', gaji: '?', dbNama: 'Budi', dbGaji: 5000000 } },
      { rowNumber: 3, values: { nama: 'Budi', gaji: 5000000, dbNama: 'Andi', dbGaji: 6500000 } },
      { rowNumber: 4, values: { nama: 'Siti', gaji: 5500000, dbNama: 'Siti', dbGaji: 5500000 } },
    ],
    validFormulas: [
      '=INDEX(E2:E4, MATCH(A2, D2:D4, 0))',
      '=INDEX(E2:E4,MATCH(A2,D2:D4,0))',
      '=XLOOKUP(A2, D2:D4, E2:E4)',
    ],
    acceptedAnswers: [6500000],
    hints: ['Ketik =INDEX(E2:E4, MATCH(A2, D2:D4, 0)).'],
    explanation: 'MATCH menemukan Andi di baris ke-2, lalu INDEX mengambil gaji baris ke-2 = Rp6.500.000.',
    samplePlaceholder: '=INDEX(E2:E4, MATCH(A2, D2:D4, 0))',
    theory: {
      concept: 'Kombinasi klasik legendaris Excel sebelum era XLOOKUP untuk pencarian ke kiri maupun ke kanan.',
      whyItMatters: 'Wajib dipahami karena banyak perusahaan masih memakai spreadsheet formula lama.',
      syntax: '=INDEX(range_hasil, MATCH(kunci, range_kunci, 0))',
      example: '=INDEX(E2:E4, MATCH(A2, D2:D4, 0))',
    },
  },

  // ========================================================
  // BAB 6: ANALISIS BISNIS & FINANSIAL (Modul 37 - 40)
  // ========================================================
  {
    id: 37,
    chapterId: 6,
    title: 'Modul 37: Laporan Laba Rugi Sederhana',
    category: 'Bisnis',
    difficulty: 'Menengah',
    scenario: 'Menghitung Laba Bersih Usaha: Pendapatan Omset Rp50.000.000 (B2) dikurangi Harga Pokok Penjualan HPP Rp30.000.000 (B3) dan Beban Operasional Rp8.000.000 (B4).',
    objective: 'Hitung Laba Bersih pada sel B5 dengan rumus =B2-B3-B4.',
    targetCell: 'B5',
    targetRowNumber: 5,
    targetColKey: 'nominal',
    targetColLetter: 'B',
    columns: [
      { key: 'akun', label: 'Komponen Laporan Keuangan', letter: 'A' },
      { key: 'nominal', label: 'Nominal (Rp)', letter: 'B' },
    ],
    rows: [
      { rowNumber: 2, values: { akun: '1. Pendapatan Penjualan (Omset)', nominal: 50000000 } },
      { rowNumber: 3, values: { akun: '2. Harga Pokok Penjualan (HPP)', nominal: 30000000 } },
      { rowNumber: 4, values: { akun: '3. Beban Operasional & Gaji', nominal: 8000000 } },
    ],
    totalLabelRow: { label: 'Laba Bersih Usaha (Net Profit):', colSpan: 1 },
    validFormulas: ['=B2-B3-B4', '=B2-(B3+B4)'],
    acceptedAnswers: [12000000],
    hints: ['Ketik =B2-B3-B4.'],
    explanation: 'Rp50.000.000 - Rp30.000.000 - Rp8.000.000 = Rp12.000.000.',
    samplePlaceholder: '=B2-B3-B4',
    theory: {
      concept: 'Laba Bersih = Pendapatan - HPP - Beban Operasional.',
      whyItMatters: 'Mengetahui keuntungan riil sebuah bisnis atau proyek.',
      syntax: '=omset - hpp - beban',
      example: '=B2 - B3 - B4',
    },
  },
  {
    id: 38,
    chapterId: 6,
    title: 'Modul 38: Menghitung Margin Keuntungan Bersih (%)',
    category: 'Bisnis',
    difficulty: 'Menengah',
    scenario: 'Menghitung Margin Profit (%): Laba Bersih Rp12.000.000 (B3) dibagi Total Pendapatan Omset Rp50.000.000 (B2).',
    objective: 'Hitung margin persentase laba pada sel B4 menggunakan rumus =B3/B2.',
    targetCell: 'B4',
    targetRowNumber: 4,
    targetColKey: 'nilai',
    targetColLetter: 'B',
    columns: [
      { key: 'item', label: 'Indikator Keuangan', letter: 'A' },
      { key: 'nilai', label: 'Nilai', letter: 'B' },
    ],
    rows: [
      { rowNumber: 2, values: { item: 'Total Pendapatan (Omset)', nilai: 50000000 } },
      { rowNumber: 3, values: { item: 'Laba Bersih (Net Profit)', nilai: 12000000 } },
    ],
    totalLabelRow: { label: 'Net Profit Margin (%):', colSpan: 1 },
    validFormulas: ['=B3/B2'],
    acceptedAnswers: [0.24],
    hints: ['Ketik =B3/B2 (Hasilnya 0.24 atau 24%).'],
    explanation: 'Rp12.000.000 / Rp50.000.000 = 0.24 (24% Profit Margin).',
    samplePlaceholder: '=B3/B2',
    theory: {
      concept: 'Net Profit Margin = Laba Bersih / Omset.',
      whyItMatters: 'Mengukur efisiensi dan kesehatan finansial perusahaan.',
      syntax: '=laba_bersih / omset',
      example: '=B3 / B2',
    },
  },
  {
    id: 39,
    chapterId: 6,
    title: 'Modul 39: Simulasi Cicilan Kredit Pinjaman (PMT)',
    category: 'Finansial',
    difficulty: 'Lanjutan',
    scenario: 'Pinjaman modal usaha Rp12.000.000 (B2), bunga bulanan 1% atau 0.01 (B3), tenor cicilan 12 bulan (B4).',
    objective: 'Hitung cicilan per bulan pada sel B5 menggunakan rumus =PMT(B3, B4, B2).',
    targetCell: 'B5',
    targetRowNumber: 5,
    targetColKey: 'nominal',
    targetColLetter: 'B',
    columns: [
      { key: 'param', label: 'Parameter Kredit', letter: 'A' },
      { key: 'nominal', label: 'Nilai', letter: 'B' },
    ],
    rows: [
      { rowNumber: 2, values: { param: 'Plafon Pinjaman (Rp)', nominal: 12000000 } },
      { rowNumber: 3, values: { param: 'Bunga Bulanan', nominal: 0.01 } },
      { rowNumber: 4, values: { param: 'Lama Cicilan (Bulan)', nominal: 12 } },
    ],
    totalLabelRow: { label: 'Angsuran Cicilan per Bulan (Rp):', colSpan: 1 },
    validFormulas: ['=PMT(B3, B4, B2)', '=PMT(B3,B4,B2)'],
    acceptedAnswers: [1066185],
    hints: ['Ketik =PMT(B3, B4, B2).'],
    explanation: 'Cicilan per bulan adalah Rp1.066.185.',
    samplePlaceholder: '=PMT(B3, B4, B2)',
    theory: {
      concept: 'PMT(rate, nper, pv) menghitung nilai angsuran pinjaman berkala.',
      whyItMatters: 'Simulasi kredit mobil, KPR rumah, atau pinjaman modal usaha.',
      syntax: '=PMT(bunga_per_periode, jumlah_periode, pinjaman_awal)',
      example: '=PMT(B3, B4, B2)',
    },
  },
  {
    id: 40,
    chapterId: 6,
    title: 'Modul 40: Analisis Titik Impas / Break Even Point (BEP Unit)',
    category: 'Bisnis',
    difficulty: 'Lanjutan',
    scenario: 'Biaya Tetap Sewa Toko Rp10.000.000 (B2), Harga Jual per Pcs Rp50.000 (B3), Biaya Variabel Pembuatan per Pcs Rp30.000 (B4).',
    objective: 'Hitung BEP jumlah unit yang harus terjual agar impas pada sel B5 dengan rumus =B2/(B3-B4).',
    targetCell: 'B5',
    targetRowNumber: 5,
    targetColKey: 'hasil',
    targetColLetter: 'B',
    columns: [
      { key: 'item', label: 'Variabel Produksi', letter: 'A' },
      { key: 'hasil', label: 'Nilai (Rp)', letter: 'B' },
    ],
    rows: [
      { rowNumber: 2, values: { item: '1. Biaya Tetap Operasional (Fixed Cost)', hasil: 10000000 } },
      { rowNumber: 3, values: { item: '2. Harga Jual per Unit', hasil: 50000 } },
      { rowNumber: 4, values: { item: '3. Biaya Variabel per Unit (HPP)', hasil: 30000 } },
    ],
    totalLabelRow: { label: 'Target BEP Impas (Unit):', colSpan: 1 },
    validFormulas: ['=B2/(B3-B4)', '=B2 / (B3 - B4)'],
    acceptedAnswers: [500],
    hints: ['Ketik =B2/(B3-B4).'],
    explanation: 'BEP = Rp10.000.000 / (Rp50.000 - Rp30.000) = 500 Unit terjual agar tidak rugi.',
    samplePlaceholder: '=B2/(B3-B4)',
    theory: {
      concept: 'BEP (Break Even Point) = Biaya Tetap / (Harga Jual - Biaya Variabel).',
      whyItMatters: 'Mengetahui target minimum penjualan agar bisnis balik modal.',
      syntax: '=biaya_tetap / (harga - biaya_variabel)',
      example: '=B2 / (B3 - B4)',
    },
  },
];

export const SANDBOX_TEMPLATES: SandboxTemplate[] = [
  {
    id: 'blank',
    name: 'Lembar Kosong (Blank Sheet)',
    description: 'Lembar kerja kosong untuk mengetik formula dan membuat tabel bebas.',
    columns: [
      { key: 'colA', label: 'Kolom A', letter: 'A' },
      { key: 'colB', label: 'Kolom B', letter: 'B' },
      { key: 'colC', label: 'Kolom C', letter: 'C' },
      { key: 'colD', label: 'Kolom D', letter: 'D' },
      { key: 'colE', label: 'Kolom E', letter: 'E' },
    ],
    rows: [
      { rowNumber: 2, values: { colA: '', colB: '', colC: '', colD: '', colE: '' } },
      { rowNumber: 3, values: { colA: '', colB: '', colC: '', colD: '', colE: '' } },
      { rowNumber: 4, values: { colA: '', colB: '', colC: '', colD: '', colE: '' } },
      { rowNumber: 5, values: { colA: '', colB: '', colC: '', colD: '', colE: '' } },
      { rowNumber: 6, values: { colA: '', colB: '', colC: '', colD: '', colE: '' } },
    ],
  },
  {
    id: 'keuangan',
    name: 'Catatan Keuangan Bulanan',
    description: 'Template arus kas pengeluaran dengan kolom Kategori dan Nominal.',
    columns: [
      { key: 'pos', label: 'Pos Kebutuhan', letter: 'A' },
      { key: 'kategori', label: 'Kategori', letter: 'B' },
      { key: 'nominal', label: 'Nominal (Rp)', letter: 'C' },
      { key: 'status', label: 'Status', letter: 'D' },
    ],
    rows: [
      { rowNumber: 2, values: { pos: 'Sewa Kost', kategori: 'Tempat Tinggal', nominal: 900000, status: 'Lunas' } },
      { rowNumber: 3, values: { pos: 'Makan & Minum', kategori: 'Konsumsi', nominal: 1200000, status: 'Lunas' } },
      { rowNumber: 4, values: { pos: 'Listrik & Air', kategori: 'Utilitas', nominal: 200000, status: 'Lunas' } },
      { rowNumber: 5, values: { pos: 'Paket Data Internet', kategori: 'Utilitas', nominal: 150000, status: 'Lunas' } },
      { rowNumber: 6, values: { pos: 'Bensin & Transport', kategori: 'Transport', nominal: 350000, status: 'Lunas' } },
      { rowNumber: 7, values: { pos: 'Tabungan Darurat', kategori: 'Investasi', nominal: 500000, status: 'Simpan' } },
    ],
  },
  {
    id: 'nilai',
    name: 'Daftar Nilai Siswa',
    description: 'Template nilai tugas, ujian, rata-rata, dan evaluasi kelulusan.',
    columns: [
      { key: 'nama', label: 'Nama Siswa', letter: 'A' },
      { key: 'tugas', label: 'Nilai Tugas', letter: 'B' },
      { key: 'uts', label: 'Nilai UTS', letter: 'C' },
      { key: 'uas', label: 'Nilai UAS', letter: 'D' },
      { key: 'rata', label: 'Rata-Rata', letter: 'E' },
    ],
    rows: [
      { rowNumber: 2, values: { nama: 'Budi Santoso', tugas: 85, uts: 80, uas: 90, rata: '=AVERAGE(B2:D2)' } },
      { rowNumber: 3, values: { nama: 'Siti Rahma', tugas: 90, uts: 95, uas: 88, rata: '=AVERAGE(B3:D3)' } },
      { rowNumber: 4, values: { nama: 'Andi Wijaya', tugas: 75, uts: 70, uas: 80, rata: '=AVERAGE(B4:D4)' } },
      { rowNumber: 5, values: { nama: 'Dewi Lestari', tugas: 88, uts: 85, uas: 92, rata: '=AVERAGE(B5:D5)' } },
    ],
  },
  {
    id: 'kasir',
    name: 'Kasir & Daftar Harga',
    description: 'Template nota kasir dengan perkalian subtotal dan pencarian harga barang.',
    columns: [
      { key: 'kode', label: 'Kode Item', letter: 'A' },
      { key: 'barang', label: 'Nama Barang', letter: 'B' },
      { key: 'qty', label: 'Jumlah (Pcs)', letter: 'C' },
      { key: 'harga', label: 'Harga Satuan (Rp)', letter: 'D' },
      { key: 'subtotal', label: 'Subtotal (Rp)', letter: 'E' },
    ],
    rows: [
      { rowNumber: 2, values: { kode: 'BRG-01', barang: 'Beras 5Kg', qty: 2, harga: 70000, subtotal: '=C2*D2' } },
      { rowNumber: 3, values: { kode: 'BRG-02', barang: 'Minyak 2L', qty: 3, harga: 32000, subtotal: '=C3*D3' } },
      { rowNumber: 4, values: { kode: 'BRG-03', barang: 'Gula 1Kg', qty: 4, harga: 16000, subtotal: '=C4*D4' } },
      { rowNumber: 5, values: { kode: 'BRG-04', barang: 'Telur 1Kg', qty: 2, harga: 28000, subtotal: '=C5*D5' } },
    ],
  },
];
